<?php
/**
 * BookingApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fareharbor API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * BookingApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BookingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bookingTour
     *
     * Booking tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\BookingResponse
     */
    public function bookingTour($company_short_name, $availability_id, $body = null)
    {
        list($response) = $this->bookingTourWithHttpInfo($company_short_name, $availability_id, $body);
        return $response;
    }

    /**
     * Operation bookingTourWithHttpInfo
     *
     * Booking tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\BookingResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function bookingTourWithHttpInfo($company_short_name, $availability_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\BookingResponse';
        $request = $this->bookingTourRequest($company_short_name, $availability_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BookingResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bookingTourAsync
     *
     * Booking tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bookingTourAsync($company_short_name, $availability_id, $body = null)
    {
        return $this->bookingTourAsyncWithHttpInfo($company_short_name, $availability_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bookingTourAsyncWithHttpInfo
     *
     * Booking tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bookingTourAsyncWithHttpInfo($company_short_name, $availability_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\BookingResponse';
        $request = $this->bookingTourRequest($company_short_name, $availability_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bookingTour'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bookingTourRequest($company_short_name, $availability_id, $body = null)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling bookingTour'
            );
        }
        // verify the required parameter 'availability_id' is set
        if ($availability_id === null || (is_array($availability_id) && count($availability_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $availability_id when calling bookingTour'
            );
        }

        $resourcePath = '/companies/{company-short-name}/availabilities/{availability-id}/bookings/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($availability_id !== null) {
            $resourcePath = str_replace(
                '{' . 'availability-id' . '}',
                ObjectSerializer::toPathValue($availability_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteBooking
     *
     * Cancel a booking
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AvailabilitiesList
     */
    public function deleteBooking($company_short_name, $booking_id)
    {
        list($response) = $this->deleteBookingWithHttpInfo($company_short_name, $booking_id);
        return $response;
    }

    /**
     * Operation deleteBookingWithHttpInfo
     *
     * Cancel a booking
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AvailabilitiesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteBookingWithHttpInfo($company_short_name, $booking_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->deleteBookingRequest($company_short_name, $booking_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AvailabilitiesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteBookingAsync
     *
     * Cancel a booking
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteBookingAsync($company_short_name, $booking_id)
    {
        return $this->deleteBookingAsyncWithHttpInfo($company_short_name, $booking_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteBookingAsyncWithHttpInfo
     *
     * Cancel a booking
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteBookingAsyncWithHttpInfo($company_short_name, $booking_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->deleteBookingRequest($company_short_name, $booking_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteBooking'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function deleteBookingRequest($company_short_name, $booking_id)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling deleteBooking'
            );
        }
        // verify the required parameter 'booking_id' is set
        if ($booking_id === null || (is_array($booking_id) && count($booking_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $booking_id when calling deleteBooking'
            );
        }

        $resourcePath = '/companies/{company-short-name}/bookings/{booking-id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($booking_id !== null) {
            $resourcePath = str_replace(
                '{' . 'booking-id' . '}',
                ObjectSerializer::toPathValue($booking_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBookingDetail
     *
     * Get booking details
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AvailabilitiesList
     */
    public function getBookingDetail($company_short_name, $booking_id)
    {
        list($response) = $this->getBookingDetailWithHttpInfo($company_short_name, $booking_id);
        return $response;
    }

    /**
     * Operation getBookingDetailWithHttpInfo
     *
     * Get booking details
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AvailabilitiesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBookingDetailWithHttpInfo($company_short_name, $booking_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getBookingDetailRequest($company_short_name, $booking_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AvailabilitiesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBookingDetailAsync
     *
     * Get booking details
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBookingDetailAsync($company_short_name, $booking_id)
    {
        return $this->getBookingDetailAsyncWithHttpInfo($company_short_name, $booking_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBookingDetailAsyncWithHttpInfo
     *
     * Get booking details
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBookingDetailAsyncWithHttpInfo($company_short_name, $booking_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getBookingDetailRequest($company_short_name, $booking_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBookingDetail'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getBookingDetailRequest($company_short_name, $booking_id)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling getBookingDetail'
            );
        }
        // verify the required parameter 'booking_id' is set
        if ($booking_id === null || (is_array($booking_id) && count($booking_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $booking_id when calling getBookingDetail'
            );
        }

        $resourcePath = '/companies/{company-short-name}/bookings/{booking-id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($booking_id !== null) {
            $resourcePath = str_replace(
                '{' . 'booking-id' . '}',
                ObjectSerializer::toPathValue($booking_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation validateBookingTour
     *
     * Validate bookings
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\BookingValidateResponse
     */
    public function validateBookingTour($company_short_name, $availability_id, $body = null)
    {
        list($response) = $this->validateBookingTourWithHttpInfo($company_short_name, $availability_id, $body);
        return $response;
    }

    /**
     * Operation validateBookingTourWithHttpInfo
     *
     * Validate bookings
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\BookingValidateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateBookingTourWithHttpInfo($company_short_name, $availability_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\BookingValidateResponse';
        $request = $this->validateBookingTourRequest($company_short_name, $availability_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BookingValidateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation validateBookingTourAsync
     *
     * Validate bookings
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateBookingTourAsync($company_short_name, $availability_id, $body = null)
    {
        return $this->validateBookingTourAsyncWithHttpInfo($company_short_name, $availability_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateBookingTourAsyncWithHttpInfo
     *
     * Validate bookings
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateBookingTourAsyncWithHttpInfo($company_short_name, $availability_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\BookingValidateResponse';
        $request = $this->validateBookingTourRequest($company_short_name, $availability_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateBookingTour'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function validateBookingTourRequest($company_short_name, $availability_id, $body = null)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling validateBookingTour'
            );
        }
        // verify the required parameter 'availability_id' is set
        if ($availability_id === null || (is_array($availability_id) && count($availability_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $availability_id when calling validateBookingTour'
            );
        }

        $resourcePath = '/companies/{company-short-name}/availabilities/{availability-id}/bookings/validate/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($availability_id !== null) {
            $resourcePath = str_replace(
                '{' . 'availability-id' . '}',
                ObjectSerializer::toPathValue($availability_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
