<?php
/**
 * CustomerTypeRateAvailability
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fareharbor API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * CustomerTypeRateAvailability Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerTypeRateAvailability implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CustomerTypeRateAvailability';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'customer_prototype' => '\Swagger\Client\Model\CustomerPrototype',
'capacity' => 'int',
'minimum_party_size' => 'int',
'customer_type' => '\Swagger\Client\Model\CustomerType',
'maximum_party_size' => 'int',
'pk' => 'int'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'customer_prototype' => null,
'capacity' => null,
'minimum_party_size' => null,
'customer_type' => null,
'maximum_party_size' => null,
'pk' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'customer_prototype' => 'customer_prototype',
'capacity' => 'capacity',
'minimum_party_size' => 'minimum_party_size',
'customer_type' => 'customer_type',
'maximum_party_size' => 'maximum_party_size',
'pk' => 'pk'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'customer_prototype' => 'setCustomerPrototype',
'capacity' => 'setCapacity',
'minimum_party_size' => 'setMinimumPartySize',
'customer_type' => 'setCustomerType',
'maximum_party_size' => 'setMaximumPartySize',
'pk' => 'setPk'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'customer_prototype' => 'getCustomerPrototype',
'capacity' => 'getCapacity',
'minimum_party_size' => 'getMinimumPartySize',
'customer_type' => 'getCustomerType',
'maximum_party_size' => 'getMaximumPartySize',
'pk' => 'getPk'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['customer_prototype'] = isset($data['customer_prototype']) ? $data['customer_prototype'] : null;
        $this->container['capacity'] = isset($data['capacity']) ? $data['capacity'] : null;
        $this->container['minimum_party_size'] = isset($data['minimum_party_size']) ? $data['minimum_party_size'] : null;
        $this->container['customer_type'] = isset($data['customer_type']) ? $data['customer_type'] : null;
        $this->container['maximum_party_size'] = isset($data['maximum_party_size']) ? $data['maximum_party_size'] : null;
        $this->container['pk'] = isset($data['pk']) ? $data['pk'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets customer_prototype
     *
     * @return \Swagger\Client\Model\CustomerPrototype
     */
    public function getCustomerPrototype()
    {
        return $this->container['customer_prototype'];
    }

    /**
     * Sets customer_prototype
     *
     * @param \Swagger\Client\Model\CustomerPrototype $customer_prototype customer_prototype
     *
     * @return $this
     */
    public function setCustomerPrototype($customer_prototype)
    {
        $this->container['customer_prototype'] = $customer_prototype;

        return $this;
    }

    /**
     * Gets capacity
     *
     * @return int
     */
    public function getCapacity()
    {
        return $this->container['capacity'];
    }

    /**
     * Sets capacity
     *
     * @param int $capacity capacity
     *
     * @return $this
     */
    public function setCapacity($capacity)
    {
        $this->container['capacity'] = $capacity;

        return $this;
    }

    /**
     * Gets minimum_party_size
     *
     * @return int
     */
    public function getMinimumPartySize()
    {
        return $this->container['minimum_party_size'];
    }

    /**
     * Sets minimum_party_size
     *
     * @param int $minimum_party_size minimum_party_size
     *
     * @return $this
     */
    public function setMinimumPartySize($minimum_party_size)
    {
        $this->container['minimum_party_size'] = $minimum_party_size;

        return $this;
    }

    /**
     * Gets customer_type
     *
     * @return \Swagger\Client\Model\CustomerType
     */
    public function getCustomerType()
    {
        return $this->container['customer_type'];
    }

    /**
     * Sets customer_type
     *
     * @param \Swagger\Client\Model\CustomerType $customer_type customer_type
     *
     * @return $this
     */
    public function setCustomerType($customer_type)
    {
        $this->container['customer_type'] = $customer_type;

        return $this;
    }

    /**
     * Gets maximum_party_size
     *
     * @return int
     */
    public function getMaximumPartySize()
    {
        return $this->container['maximum_party_size'];
    }

    /**
     * Sets maximum_party_size
     *
     * @param int $maximum_party_size maximum_party_size
     *
     * @return $this
     */
    public function setMaximumPartySize($maximum_party_size)
    {
        $this->container['maximum_party_size'] = $maximum_party_size;

        return $this;
    }

    /**
     * Gets pk
     *
     * @return int
     */
    public function getPk()
    {
        return $this->container['pk'];
    }

    /**
     * Sets pk
     *
     * @param int $pk pk
     *
     * @return $this
     */
    public function setPk($pk)
    {
        $this->container['pk'] = $pk;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
