<?php
/**
 * BookingResponseObjectTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fareharbor API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * BookingResponseObjectTest Class Doc Comment
 *
 * @category    Class
 * @description BookingResponseObject
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BookingResponseObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BookingResponseObject"
     */
    public function testBookingResponseObject()
    {
    }

    /**
     * Test attribute "voucher_number"
     */
    public function testPropertyVoucherNumber()
    {
    }

    /**
     * Test attribute "rebooked_to"
     */
    public function testPropertyRebookedTo()
    {
    }

    /**
     * Test attribute "rebooked_from"
     */
    public function testPropertyRebookedFrom()
    {
    }

    /**
     * Test attribute "receipt_subtotal"
     */
    public function testPropertyReceiptSubtotal()
    {
    }

    /**
     * Test attribute "receipt_total_display"
     */
    public function testPropertyReceiptTotalDisplay()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "note_safe_html"
     */
    public function testPropertyNoteSafeHtml()
    {
    }

    /**
     * Test attribute "agent"
     */
    public function testPropertyAgent()
    {
    }

    /**
     * Test attribute "pk"
     */
    public function testPropertyPk()
    {
    }

    /**
     * Test attribute "uuid"
     */
    public function testPropertyUuid()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "confirmation_url"
     */
    public function testPropertyConfirmationUrl()
    {
    }

    /**
     * Test attribute "dashboard_url"
     */
    public function testPropertyDashboardUrl()
    {
    }

    /**
     * Test attribute "customer_count"
     */
    public function testPropertyCustomerCount()
    {
    }

    /**
     * Test attribute "invoice_price_display"
     */
    public function testPropertyInvoicePriceDisplay()
    {
    }

    /**
     * Test attribute "display_id"
     */
    public function testPropertyDisplayId()
    {
    }

    /**
     * Test attribute "pickup"
     */
    public function testPropertyPickup()
    {
    }

    /**
     * Test attribute "availability"
     */
    public function testPropertyAvailability()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "customers"
     */
    public function testPropertyCustomers()
    {
    }

    /**
     * Test attribute "invoice_price"
     */
    public function testPropertyInvoicePrice()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }
}
